[2024-10-15T13:12:14.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-15T13:12:14.480+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: news_scraping_pipeline.clean_data_task manual__2024-10-15T13:11:37.430344+00:00 [queued]>
[2024-10-15T13:12:14.509+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: news_scraping_pipeline.clean_data_task manual__2024-10-15T13:11:37.430344+00:00 [queued]>
[2024-10-15T13:12:14.513+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-15T13:12:14.545+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): clean_data_task> on 2024-10-15 13:11:37.430344+00:00
[2024-10-15T13:12:14.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'news_scraping_pipeline', 'clean_data_task', 'manual__2024-10-15T13:11:37.430344+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/news_scraping_pipeline.py', '--cfg-path', '/tmp/tmpc0yd0poj']
[2024-10-15T13:12:14.577+0000] {standard_task_runner.py:105} INFO - Job 53: Subtask clean_data_task
[2024-10-15T13:12:14.578+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=498) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-15T13:12:14.580+0000] {standard_task_runner.py:72} INFO - Started process 500 to run task
[2024-10-15T13:12:14.698+0000] {task_command.py:467} INFO - Running <TaskInstance: news_scraping_pipeline.clean_data_task manual__2024-10-15T13:11:37.430344+00:00 [running]> on host 81639b321f8c
[2024-10-15T13:12:15.004+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='news_scraping_pipeline' AIRFLOW_CTX_TASK_ID='clean_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T13:11:37.430344+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-15T13:11:37.430344+00:00'
[2024-10-15T13:12:15.031+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-15T13:12:15.033+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-15T13:12:15.035+0000] {logging_mixin.py:190} INFO - Current task name:clean_data_task state:running start_date:2024-10-15 13:12:14.487825+00:00
[2024-10-15T13:12:15.045+0000] {logging_mixin.py:190} INFO - Dag name:news_scraping_pipeline and current dag run status:running
[2024-10-15T13:12:15.046+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-15T13:12:15.082+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_scraping_pipeline.py", line 67, in clean_data_task
    raise ValueError("No articles found to clean")
ValueError: No articles found to clean
[2024-10-15T13:12:15.183+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-10-15T13:12:15.185+0000] {logging_mixin.py:190} INFO - Task start:2024-10-15 13:12:14.487825+00:00 end:2024-10-15 13:12:15.182369+00:00 duration:0.694544
[2024-10-15T13:12:15.196+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): clean_data_task> dag:<DAG: news_scraping_pipeline> dagrun:<DagRun news_scraping_pipeline @ 2024-10-15 13:11:37.430344+00:00: manual__2024-10-15T13:11:37.430344+00:00, state:running, queued_at: 2024-10-15 13:11:37.555341+00:00. externally triggered: True>
[2024-10-15T13:12:15.198+0000] {logging_mixin.py:190} INFO - Failure caused by No articles found to clean
[2024-10-15T13:12:15.200+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=news_scraping_pipeline, task_id=clean_data_task, run_id=manual__2024-10-15T13:11:37.430344+00:00, execution_date=20241015T131137, start_date=20241015T131214, end_date=20241015T131215
[2024-10-15T13:12:15.344+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-15T13:12:15.355+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 53 for task clean_data_task (No articles found to clean; 500)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/news_scraping_pipeline.py", line 67, in clean_data_task
    raise ValueError("No articles found to clean")
ValueError: No articles found to clean
[2024-10-15T13:12:15.573+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-15T13:12:15.693+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-15T13:12:15.725+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
